# this workflow copy a helm values file from dev github repo (for dev anv) to production github repo(for production env)
#the repos are thealmost the same and we edit the values file in the dev env for testing. when its done we want the same changes in production repo
#it is made with clone the dev copy the file to another dir then clone production repo for the push
#then chaging the content of the values file to the wanted content and pushing it back to production repo for argo to update the app 

name: CD - push from dev to production

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      env:
           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
# make temp dir for values.yaml file that is taken from argo_dev repo
# mv the file to the temp repo and renaming it from "values.yaml" to "temp-values.yaml"
# switch "nodePort" value field from 30101(of dev env) to 30100(of production env) 
      run: |
            mkdir /home/runner/work/temp 
            mv ./dev/values.yaml /home/runner/work/temp/temp-values.yaml 
            sed -i 's/nodePort: 30101/nodePort: 30100/g' /home/runner/work/temp/temp-values.yaml
# clone argo_production repo for the push latter (using TOKEN for permision)
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'shiranitz'
        repository: 'argo_production'
        access-token: ${{ secrets.API_TOKEN_GITHUB }}
# mv argo_production to one diractory back
# deleting the argo_dev local git repo
# override the content of temp-values.yaml file to values.yaml file
# moving to argo_production local git dir of repo for pushing
# addin deteiles about acount on config file 
# pushing new values.yaml file to production repo
# puting back the argo_dev dir for cleanup chackout(it is the original path of the first checkout)
    - name: after clone
      run: |  
            mv /home/runner/work/argo_dev/argo_dev/argo_production /home/runner/work/argo_dev/argo_production
            echo "move production dir"
            
            rm -rf /home/runner/work/argo_dev/argo_dev
            echo "rm for dev dir"
            
            cat /home/runner/work/temp/temp-values.yaml > /home/runner/work/argo_dev/argo_production/values.yaml
            echo "copy content from tamp-values.yaml to values.yaml"
            
            cd /home/runner/work/argo_dev/argo_production
            echo " cd to prod dir"
            
            git config --global user.email "shiranitz15@gmail.com"
            git config --global user.name "shiranitz"
            echo "tell you how i am"
            
            git add values.yaml
            git status
            git commit -m .
            git push origin main
            
            mkdir /home/runner/work/argo_dev/argo_dev
