name: CD - push from dev to production

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      env:
           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
            mkdir /home/runner/work/temp 
            mv ./dev/values.yaml /home/runner/work/temp/temp-values.yaml 
            sed -i 's/nodePort: 30101/nodePort: 30100/g' /home/runner/work/temp/temp-values.yaml
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'shiranitz'
        repository: 'argo_production'
        access-token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: after clone
      run: |  
            mv /home/runner/work/argo_dev/argo_dev/argo_production /home/runner/work/argo_dev/argo_production
            echo "move production dir"
            
            rm -rf /home/runner/work/argo_dev/argo_dev
            echo "rm for dev dir"
            
            cat /home/runner/work/temp/temp-values.yaml > /home/runner/work/argo_dev/argo_production/values.yaml
            echo "copy content from tamp-values.yaml to values.yaml"
            
            cd /home/runner/work/argo_dev/argo_production
            echo " cd to prod dir"
            
            git config --global user.email "shiranitz15@gmail.com"
            git config --global user.name "shiranitz"
            echo "tell you how i am"
            
            git add values.yaml
            git status
            git commit -m .
            git push origin main
            
            mkdir /home/runner/work/argo_dev/argo_dev
