name: CD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  deploy:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3

#      - name: Pushes to another repository
#        uses: cpina/github-action-push-to-another-repository@main
 #       env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#         with:
#           source-directory: dev
#           destination-github-username: shiranitz  
#           destination-repository-name: argo_production
#           user-email: shiranitz15@gmail.com
#           target-branch: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      env:
           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
            pwd
            ls
            mkdir /home/runner/work/temp 
            mv ./dev/values.yaml /home/runner/work/temp/temp-values.yaml
            echo "----BEFORE switch port with sed-----"
            cat /home/runner/work/temp/temp-values.yaml
            
            chmode +w /home/runner/work/temp/temp-values.yaml
            sudo sed -i 's/nodeport: 30101/nodeport: 30100/g' /home/runner/work/temp/temp-values.yaml
            
            echo "----AFTER switch port with sed-----"
            cat /home/runner/work/temp/temp-values.yaml
            
            
            ls -A /home/runner/work/argo_dev/argo_dev
#            mv /home/runner/work/argo_dev /home/runner/work/argo_production 
#            rm -rf /home/runner/work/argo_production/argo_dev
#            cd /home/runner/work/argo_production
#            pwd
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'shiranitz'
        repository: 'argo_production'
        access-token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: after clone
      run: |
            pwd
            echo "cloning production"
            
            ls -A /home/runner/work/argo_dev/argo_dev
            echo "ls argo_production"
            
            mv /home/runner/work/argo_dev/argo_dev/argo_production /home/runner/work/argo_dev/argo_production
            echo "move production dir"
            
            ls -A /home/runner/work/argo_dev
            echo "ls for /home/runner/work/argo_dev"
            
            rm -rf /home/runner/work/argo_dev/argo_dev
            echo "rm for dev dir"
            
            ls -A /home/runner/work/argo_dev
            echo "ls for /home/runner/work/argo_dev"
            
            cat /home/runner/work/argo_dev/argo_production/values.yaml
            echo "cat befire copy"
            
            echo "----BEFORE switch port with sed-----"
            cat /home/runner/work/temp/temp-values.yaml
            
            sed -i 's/nodeport: 30101/nodeport: 30100/g' /home/runner/work/temp/temp-values.yaml
            
            echo "----AFTER switch port with sed-----"
            cat /home/runner/work/temp/temp-values.yaml
            
            
            sed -i 's/nodeport: 30101/nodeport: 30100/g' /home/runner/work/temp/temp-values.yaml
            cat /home/runner/work/temp/temp-values.yaml > /home/runner/work/argo_dev/argo_production/values.yaml
            echo "edit port and copy"
            
            cat /home/runner/work/argo_dev/argo_production/values.yaml
            echo "cat affter copy"
            
            cd /home/runner/work/argo_dev/argo_production
            pwd
            ls -A
            echo " cd to prod dir"
            
            git config --global user.email "shiranitz15@gmail.com"
            git config --global user.name "shiranitz"
            echo "tell you how i am"
            
            git remote -v
            echo "what is my remote"
            
            git status
            git add values.yaml
            git status
            git commit -m .
            git push origin main
            
            
            /home/runner/work/argo_dev/argo_dev
            git remote -v
            git remote set-url origin https://github.com/shiranitz/argo_production
            git remote -v
            git config --global user.email "shiranitz15@gmail.com"
            git config --global user.name "shiranitz"
            git config --global --add safe.directory . 
            git status
            sed -i 's/nodeport: 30100/nodeport: 30101/g' ./dev/values.yaml
            git status
            git add ./dev/values.yaml
            git commit -m "new values"
            git push https://github.com/shiranitz/argo_production --set-upstream main
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#         github_token: ${{ secrets.API_TOKEN_GITHUB }}
 #        branch: main
 #           git push origin main
    
#    - name: change remote repo to production
#      run: |
#            git remote -v
#            git remote add origin https://github.com/shiranitz/argo_production
#            git remote -v
#    - name: Commit files
#       run: |
#         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#         git config --local user.name "shiranitz15@gmail.com]"
#         git commit -a -m "Add changes"
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.API_TOKEN_GITHUB }}
#         branch: main
